### ISSUE TITLE
Checkstyle

### ISSUE THREAD

**Issue by m-terlinde** [RUB-NDS/ModifiableVariable#13]
We got a https://github.com/RUB-NDS/ModifiableVariable/blob/master/maven-eclipse-codestyle.xml but don't use the checkstyle maven plugin at all.
Not even for reporting or something else. We should consider using the maven plugin with options ` includeTestSourceDirectory ` to `true` and create a report with every build.

**Comment by m-terlinde** [comment]
Well, I got confused by the title, it is for the format plugin.
Anyway, do we want a checkstyle plugin due to code quality?

**Comment by jurajsomorovsky** [comment]
You can always use 
mvn checkstyle:checkstyle 
to create a checkstyle report with the default configuration, see here:
https://maven.apache.org/plugins/maven-checkstyle-plugin/

I do not think we need an extra checkstyle.xml for this small project. If you it is necessary, you can create one with a pull request.
