### ISSUE TITLE
IndexOutOfBounds Exception

### ISSUE THREAD

**Issue by ic0ns** [RUB-NDS/ModifiableVariable#17]
The Modification Concept as it is now has multiple occasions where it is possible to generate IndexOutOfBounds Exceptions. Especially the XOR, Delete and Insert operation can throw this Exception when the value for which they there designed is not equally long in a future execution.

**Comment by ic0ns** [comment]
https://github.com/RUB-NDS/ModifiableVariable/tree/UnapplicableModificationsFix implements a "solution" that does not modify the variable and just returns the original value

**Comment by jurajsomorovsky** [comment]
This looks good. Maybe setting the loglevel to at least INFO would be more appropriate.

The downside is that this would have some effect on the fuzzing performance. Maybe we will come out with a different solution  in the future.
