### ISSUE TITLE
ArrayConverter bytesize gets omitted

### ISSUE THREAD

**Issue by m-terlinde** [RUB-NDS/ModifiableVariable#3]
> Please take a look at the ArrayConverter Class.
>The method in line 140 uses the bytesize value to determine, whether the pretty printing should be used >or not.
>It passes the arguments to the method in line 152. The method there omits the bytesize value and passes >the complete byte length to the next method.
>
> Is this desired behaviour?

>I guess you are right, this is a bug. But the thing is i think the byteSize parameter should not be there at >all, since it is implicitly determined by the array element. Can you fix this problem by removing the >byteSize parameter? Also note that the ModifiableVariable module is now in a seperate public repo. So >you would need to create a new branch there. Thanks for reporting

**Comment by ic0ns** [comment]
thanks
