### ISSUE TITLE
bytesToHexString with usePrettyPrinting=false small formatting issue

### ISSUE THREAD

**Issue by pfsk4tsh** [RUB-NDS/ModifiableVariable#7]
ArrayConverter.bytesToHexString does not behave as intended if the usePrettyPrinting flag is set to false. The last if statement should be evaluated only if prettyPrinting is enabled, shouldn't it? The following would be correct, I guess:

```java
         ....
         if (usePrettyPrinting && i != 0) {
                if (i % 16 == 0) {
                    result.append("\n");
                } else if (i % 8 == 0) {
                    result.append(" ");
                }
                if (i % 16 != 0) {
                    result.append(" ");
                }                
            }

         byte b = array[i];
         ....
```

(Could be expressed a bit nicer, of course :])

**Comment by ic0ns** [comment]
I am not sure if this is not a desired feature. By default we use "kindofprettyprinting" and for really long byte[] we are using "prettyprinting". Do you have a special need for "uglyprinting"?

**Comment by pfsk4tsh** [comment]
It's easier to compare an unformatted hex string with test vectors, for example. 
No problem for me if you want to always insert whitespace. I just wouldn't expect this behaviour and thought that it was not the idea. Inserting space only if (i % 16 != 0) doesn't make sense if usePrettyPrinting is false, since there won't be any whitespace after 16 bytes. Find the bytes AF45 and 9CCE the formatted version of the hex string below :]

```
335A86267F17017E313D04C79E11ACAF4553622BF566F9BAAF26E919A5EB359CCE757ACC7D9E88ADD84313A1F12A4EA0

33 5A 86 26 7F 17 01 7E 31 3D 04 C7 9E 11 AC AF45 53 62 2B F5 66 F9 BA AF 26 E9 19 A5 EB 35 9CCE 75 7A CC 7D 9E 88 AD D8 43 13 A1 F1 2A 4E A0
```

**Comment by ic0ns** [comment]
Okay I see what you mean. If you want you can implement a Version of this Method which uses no spaces, but we still need a Version with Spaces without new lines for XML Serialization.
